name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

permissions: write-all
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Run a script
        run: |
          chmod +x install.sh
          bash install.sh
